[package]
name = "esse"
version = "0.1.0"
authors = ["CympleTech <contact@cympletech.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[lib]
name = "esse"
crate-type = ["cdylib", "staticlib"]

[[bin]]
name = "esse"
path = "src/daemon.rs"

[profile.release]
opt-level = 's'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
log = "0.4"
rand = "0.8"
once_cell = "1.7"
simplelog = "0.10"
image = "0.23"
base64 = "0.13"
sha2 = "0.9"
blake3 = "0.3"
aes-gcm = "0.8"
serde = { version = "1", features = ["derive"] }
postcard = { version = "0.5", default-features = false, features = ["alloc"] }
sysinfo = "0.16"
tokio = { version = "1", features = ["full"] }
tdn = { version = "0.5", default-features = false, features = ["full"] }
tdn_did = { git = "https://github.com/cypherlink/tdn_did", branch="main" }
tdn_storage = { git = "https://github.com/cypherlink/tdn_storage", branch="main" }
group-chat_types = { git = "https://github.com/cympletech/group-chat", branch="main" }
#group-chat-types = { path = "../group-chat/types" }

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.19", default-features = false }